image: rakudo-star:latest

stages:
  - do-install
  - do-test

before_script:
  - perl6 --version
  - zef update
  - zef --debug --depsonly install git://github.com/ugexe/zef.git
  - zef upgrade zef
  - zef uninstall HTTP::UserAgent
  - zef --version

install-http-useragent:
  stage: do-install
  script:
    - zef install .
  only:
    - keepalive_dev

test-http-useragent:
  stage: do-test
  script:
    - prove6 ./t
  only:
    - keepalive_dev
