image: rakudo-star:latest

stages:
  - do-install-and-test

before_script:
  - apt-get update && apt-get install -y openssl libssl-dev
  - perl6 --version
  - zef update
  - zef --debug --depsonly install git://github.com/ugexe/zef.git
  - zef upgrade zef
  - zef uninstall HTTP::UserAgent
  - zef --version

http-useragent:
  stage: do-install-and-test
  script:
    - zef install .
    - export NETWORK_TESTING=1
    - prove -ve 'perl6 -Ilib'
    - unset NETWORK_TESTING
  only:
    - keepalive_dev
